//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace csEquationSolver.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("csEquationSolver.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About csEquationSolver.
        /// </summary>
        internal static string IDS_ABOUT_BOX_CAPTION {
            get {
                return ResourceManager.GetString("IDS_ABOUT_BOX_CAPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Program: csEquationSolver
        ///Copyright 2010-2013 William Hallahan
        ///MIT License.
        /// </summary>
        internal static string IDS_ABOUT_BOX_TEXT {
            get {
                return ResourceManager.GetString("IDS_ABOUT_BOX_TEXT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to save the current document?.
        /// </summary>
        internal static string IDS_DO_YOU_WANT_TO_SAVE_QUERY {
            get {
                return ResourceManager.GetString("IDS_DO_YOU_WANT_TO_SAVE_QUERY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Equations solved.
        /// </summary>
        internal static string IDS_EQUATIONS_SOLVED {
            get {
                return ResourceManager.GetString("IDS_EQUATIONS_SOLVED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The equation syntax is illegal..
        /// </summary>
        internal static string IDS_ERROR_ILLEGAL_EQUATION {
            get {
                return ResourceManager.GetString("IDS_ERROR_ILLEGAL_EQUATION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A number contains an illegal exponent..
        /// </summary>
        internal static string IDS_ERROR_ILLEGAL_EXPONENT {
            get {
                return ResourceManager.GetString("IDS_ERROR_ILLEGAL_EXPONENT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A number contains the &apos;^&apos; character and is missing an exponent..
        /// </summary>
        internal static string IDS_ERROR_MISSING_EXPONENT {
            get {
                return ResourceManager.GetString("IDS_ERROR_MISSING_EXPONENT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A number contains more than one decimal point..
        /// </summary>
        internal static string IDS_ERROR_MULTIPLE_DECIMAL_POINTS {
            get {
                return ResourceManager.GetString("IDS_ERROR_MULTIPLE_DECIMAL_POINTS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are multiple equal signs in the equation..
        /// </summary>
        internal static string IDS_ERROR_MULTIPLE_EQUAL_SIGNS {
            get {
                return ResourceManager.GetString("IDS_ERROR_MULTIPLE_EQUAL_SIGNS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is no equal sign in the equation..
        /// </summary>
        internal static string IDS_ERROR_NO_EQUAL_SIGN {
            get {
                return ResourceManager.GetString("IDS_ERROR_NO_EQUAL_SIGN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is no term after the equal sign in the equation..
        /// </summary>
        internal static string IDS_ERROR_NO_TERM_AFTER_EQUAL_SIGN {
            get {
                return ResourceManager.GetString("IDS_ERROR_NO_TERM_AFTER_EQUAL_SIGN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is no term before the equal sign in the equation..
        /// </summary>
        internal static string IDS_ERROR_NO_TERM_BEFORE_EQUAL_SIGN {
            get {
                return ResourceManager.GetString("IDS_ERROR_NO_TERM_BEFORE_EQUAL_SIGN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A number or a variable was expected..
        /// </summary>
        internal static string IDS_ERROR_NO_TERM_ENCOUNTERED {
            get {
                return ResourceManager.GetString("IDS_ERROR_NO_TERM_ENCOUNTERED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is no variable in the equation..
        /// </summary>
        internal static string IDS_ERROR_NO_VARIABLE_IN_EQUATION {
            get {
                return ResourceManager.GetString("IDS_ERROR_NO_VARIABLE_IN_EQUATION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A number contains more than 15 digits..
        /// </summary>
        internal static string IDS_ERROR_TOO_MANY_DIGITS {
            get {
                return ResourceManager.GetString("IDS_ERROR_TOO_MANY_DIGITS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error - the system of equations is ill conditioned..
        /// </summary>
        internal static string IDS_ILL_CONDITIONED_SYSTEM_OF_EQUATIONS {
            get {
                return ResourceManager.GetString("IDS_ILL_CONDITIONED_SYSTEM_OF_EQUATIONS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is nothing to print..
        /// </summary>
        internal static string IDS_NOTHING_TO_PRINT {
            get {
                return ResourceManager.GetString("IDS_NOTHING_TO_PRINT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is nothing to save..
        /// </summary>
        internal static string IDS_NOTHING_TO_SAVE {
            get {
                return ResourceManager.GetString("IDS_NOTHING_TO_SAVE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Document Save On Exit Query.
        /// </summary>
        internal static string IDS_SAVE_ON_EXIT_PROMPT {
            get {
                return ResourceManager.GetString("IDS_SAVE_ON_EXIT_PROMPT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error - the system of equations is singular..
        /// </summary>
        internal static string IDS_SINGULAR_SYSTEM_OF_EQUATIONS {
            get {
                return ResourceManager.GetString("IDS_SINGULAR_SYSTEM_OF_EQUATIONS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Solving equations.
        /// </summary>
        internal static string IDS_SOLVING_EQUATIONS {
            get {
                return ResourceManager.GetString("IDS_SOLVING_EQUATIONS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The equation was parsed successfully..
        /// </summary>
        internal static string IDS_SUCCESS {
            get {
                return ResourceManager.GetString("IDS_SUCCESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Only {0} equations is too few equations for {1} variables.
        /// </summary>
        internal static string IDS_TOO_FEW_EQUATIONS {
            get {
                return ResourceManager.GetString("IDS_TOO_FEW_EQUATIONS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} equations is too many equations for only {1} variables.
        /// </summary>
        internal static string IDS_TOO_MANY_EQUATIONS {
            get {
                return ResourceManager.GetString("IDS_TOO_MANY_EQUATIONS", resourceCulture);
            }
        }
    }
}
